CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"), UNIQUE ("group_id", "permission_id"));
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), UNIQUE ("user_id", "group_id"));
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"), UNIQUE ("user_id", "permission_id"));
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_groups_e8701ad4" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_0e939a4f" ON "auth_user_groups" ("group_id");
CREATE INDEX "auth_user_user_permissions_e8701ad4" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_8373b171" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id"), "user_id" integer NOT NULL REFERENCES "auth_user" ("id"));
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id");
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL, UNIQUE ("app_label", "model"));
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"), "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL, UNIQUE ("content_type_id", "codename"));
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id");
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "is_superuser" bool NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "last_login" datetime NULL);
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date");
CREATE TABLE "ModME_event" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "time" integer NOT NULL, "sessionID" varchar(500) NOT NULL, "eventType" varchar(200) NOT NULL, "chart" varchar(200) NOT NULL, "arg" varchar(200) NOT NULL, "domID" varchar(200) NOT NULL);
CREATE TABLE "ModME_mousetracking" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "time" integer NOT NULL, "sessionID" varchar(500) NOT NULL, "x" real NOT NULL, "y" real NOT NULL, "domID" varchar(200) NOT NULL, "targetX" real NOT NULL, "targetY" real NOT NULL);
CREATE TABLE "ModME_resourceswitch" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "time" integer NOT NULL, "sessionID" varchar(500) NOT NULL, "switchNumber" integer NOT NULL, "state" varchar(200) NOT NULL);
CREATE TABLE "ModME_resourcetank" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "time" integer NOT NULL, "sessionID" varchar(500) NOT NULL, "tankNumber" integer NOT NULL, "state" real NOT NULL);
CREATE TABLE "ModME_tracking" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "time" integer NOT NULL, "sessionID" varchar(500) NOT NULL, "x" real NOT NULL, "y" real NOT NULL, "domID" varchar(200) NOT NULL, "state" varchar(200) NOT NULL, "mouseX" real NOT NULL, "mouseY" real NOT NULL);
CREATE TABLE "ModME_file" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "task_id" integer NOT NULL REFERENCES "ModME_task" ("id"));
CREATE INDEX "ModME_file_57746cc8" ON "ModME_file" ("task_id");
CREATE TABLE "ModME_task" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "fileName" varchar(200) NOT NULL, "taskName" varchar(200) NOT NULL, "configurator" varchar(200) NOT NULL);
CREATE TABLE "ModME_metadata" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "startTime" integer NOT NULL, "sessionID" varchar(500) NOT NULL, "duration" varchar(500) NOT NULL, "participantID" varchar(500) NOT NULL, "sessionNumber" varchar(500) NOT NULL, "condition" varchar(500) NOT NULL, "task1" varchar(500) NOT NULL, "task2" varchar(500) NOT NULL, "task3" varchar(500) NOT NULL, "task4" varchar(500) NOT NULL);
CREATE TABLE "ModME_tableadd" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "uniqueString" varchar(30) NOT NULL, "applyed" bool NOT NULL, "tableName" varchar(100) NOT NULL);
CREATE TABLE "ModME_condition" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" varchar(200) NOT NULL, "experimentDuration" integer NOT NULL, "task1" integer NOT NULL, "task1Data" varchar(5000) NOT NULL, "task2" integer NOT NULL, "task2Data" varchar(5000) NOT NULL, "task3" integer NOT NULL, "task3Data" varchar(5000) NOT NULL, "task4" integer NOT NULL, "task4Data" varchar(5000) NOT NULL, "task1GUI" bool NOT NULL, "task2GUI" bool NOT NULL, "task3GUI" bool NOT NULL, "task4GUI" bool NOT NULL);
CREATE TABLE "ModME_survey" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "fileName" varchar(200) NOT NULL);
CREATE TABLE "ModME_condition_surveys" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "condition_id" integer NOT NULL REFERENCES "ModME_condition" ("id"), "survey_id" integer NOT NULL REFERENCES "ModME_survey" ("id"), UNIQUE ("condition_id", "survey_id"));
CREATE INDEX "ModME_condition_surveys_bb531585" ON "ModME_condition_surveys" ("condition_id");
CREATE INDEX "ModME_condition_surveys_00b3bd7e" ON "ModME_condition_surveys" ("survey_id");
CREATE TABLE "ModME_nasatlx" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sessionID" varchar(500) NOT NULL, "time" integer NOT NULL, "mental" integer NOT NULL, "physical" integer NOT NULL, "temporal" integer NOT NULL, "performance" integer NOT NULL, "effort" integer NOT NULL, "frustration" integer NOT NULL, "fatigue" integer NOT NULL, "boredom" integer NOT NULL);
CREATE TABLE "ModME_surveyfile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "task_id" integer NOT NULL REFERENCES "ModME_survey" ("id"));
CREATE INDEX "ModME_surveyfile_57746cc8" ON "ModME_surveyfile" ("task_id");
