# Generated by Django 2.2.12 on 2021-05-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModME', '0003_add_default_tasks'),
        ('ModME', '0002_add_nasa_tlx_survey'),
    ]

    operations = [
    ]
