# Generated by Django 2.2 on 2021-11-18 16:42

import ModME.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModME', '0004_merge_20210514_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='remoteExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This Remote Experiment Name should help you distiguish between remote session which run the same Experiment, but different Session and Study IDs.', max_length=75, verbose_name='Remote Experiment Name')),
                ('session_id', models.CharField(help_text='This is the Session ID', max_length=50, verbose_name='Session ID')),
                ('study_id', models.CharField(help_text='This is the Study ID', max_length=50, verbose_name='Study ID')),
                ('bulk_user_creation', models.IntegerField(blank=True, help_text='This will create a bulk number of Remote Participants for this Remote Experiment. When you select --Save-- the number you enter in this field will be the number of Remote Participants that will be generated and then the field will be reset to 0. If you require additional bulk creation of Remote Participants, simply enter a number in this field again and select --Save--', verbose_name='Bulk Participent Creation')),
                ('remote_code', models.CharField(default='5QQOUJOLHI7Z', max_length=12, verbose_name='Remote Code')),
                ('remote_link', models.CharField(default='remotelink/5QQOUJOLHI7Z/', max_length=100, verbose_name='Remote Link')),
                ('available_participants', models.IntegerField(default=0, editable=False, verbose_name='Available Participants')),
                ('hold_participants', models.IntegerField(default=0, editable=False, verbose_name='Particpant Hold')),
                ('complete_participants', models.IntegerField(default=0, editable=False, verbose_name='Paticipent Complete')),
                ('total_participants', models.IntegerField(default=0, editable=False, verbose_name='Total Participants')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModME.Experiment')),
            ],
            options={
                'verbose_name': 'Remote Experiment',
                'verbose_name_plural': 'Remote Experiments',
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='skip_instructions',
            field=models.BooleanField(default=True, help_text='Selecting this will skip the Instruction page. You should be done when participants have already been trained or have been physically given instructions.', verbose_name='Skip Condition Instruction Page'),
        ),
        migrations.CreateModel(
            name='remoteParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=ModME.models.remoteParticipant.code_generator, help_text='This is an auto generated Participant ID', max_length=20, verbose_name='Participant ID')),
                ('completion_code', models.CharField(default=ModME.models.remoteParticipant.code_generator, help_text='The participant will receive this code after they complete their experiment', max_length=20, verbose_name='Completion Code')),
                ('id_hold', models.BooleanField(default=False, help_text='This puts a hold on this user ID when a participant has started their session, however, they may not have complete the experiment', verbose_name='Hold')),
                ('id_complete', models.BooleanField(default=False, help_text='This indicates that the participant has completed their experiment', verbose_name='Complete')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ModME.remoteExperiment')),
            ],
            options={
                'verbose_name': 'Remote Participant',
                'verbose_name_plural': 'Remote Participants',
            },
        ),
    ]
