# Generated by Django 2.2 on 2022-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModME', '0006_add_example_experiment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': 'Experiment', 'verbose_name_plural': 'Experiments'},
        ),
        migrations.AlterModelOptions(
            name='nasatlx',
            options={'verbose_name': 'NASA TLX', 'verbose_name_plural': 'NASA TLX'},
        ),
        migrations.AlterField(
            model_name='condition',
            name='instructional_pdf',
            field=models.FileField(blank=True, help_text='This PDF will be displayed right before the Condition and should be used to give the participant instructions.', upload_to='static/PDF/', verbose_name='Participant Instructions'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='conditions',
            field=models.CharField(help_text='Enter the ID number of each Condition in the order you would like them to occur in the experiment (e.g. 1,3,1,2). This field is NOT visible to participants.', max_length=5000, verbose_name='conditions'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_ending_message',
            field=models.TextField(default='', help_text='This will be the message that will appear when the experiment has ended. This field is visible to participants.', verbose_name='Experiment Ending Message'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='icd_confirmation_text',
            field=models.TextField(default="By clicking the 'Next' button below, I confirm that I have read the above information, meet the eligibility criteria for participating, and agree to participate in this study.", help_text='This is the ICD confirmation text, which will be right below the PDF view of the ICD. This field is visible to participants.', verbose_name='ICD Confirmation Text'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='instructional_pdf',
            field=models.FileField(blank=True, help_text='Selecting this option will omit any instructions for this specific condition. This should only be done when participants have already been trained on what to expect or have been provided with written instructions.', upload_to='static/PDF/'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='instructional_text',
            field=models.TextField(default='', help_text='This is the text below the Instruction PDF. This field is visible to participants.', verbose_name='Instructional Confirmation Text'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='irb_pdf',
            field=models.FileField(blank=True, help_text='Please upload your IRB here. The IRB will display prior to the experiment. This form is visible to participants.', upload_to='static/PDF/', verbose_name='ICD PDF'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(help_text='This field is NOT visible to participants.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='This is for internal notes only. This will not be shown to any participant. This field is NOT visible to participants.', verbose_name='Experiment Notes'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='random',
            field=models.BooleanField(default=False, help_text='This will randomize the order of the Conditions (Note: This will negate any condition order you enter below), This field is NOT visible to participants.', verbose_name='Randomize Conditions'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='skip_irb',
            field=models.BooleanField(help_text='Selecting this will skip the Informed Consent Document page. This should ONLY be done if the participants are physically given the ICD.', verbose_name='Skip ICD Page'),
        ),
        migrations.AlterField(
            model_name='remoteexperiment',
            name='bulk_user_creation',
            field=models.IntegerField(blank=True, help_text='This will create a bulk number of Remote Participants for this Remote Experiment. When you select --Save-- the number you enter in this field will be the number of Remote Participants that will be generated and then the field will be reset to 0. If you require additional bulk creation of Remote Participants, simply enter a number in this field again and select --Save--', verbose_name='Bulk participant Creation'),
        ),
        migrations.AlterField(
            model_name='remoteexperiment',
            name='remote_code',
            field=models.CharField(default='W24STK8L78DF', max_length=12, verbose_name='Remote Code'),
        ),
        migrations.AlterField(
            model_name='remoteexperiment',
            name='remote_link',
            field=models.CharField(default='remotelink/W24STK8L78DF/', max_length=100, verbose_name='Remote Link'),
        ),
    ]
