# Generated by Django 3.2 on 2022-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModME', '0007_auto_20220406_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='This is for internal notes only. This will not be shown to any participant. This field is NOT visible to participants.', verbose_name='Condition Notes'),
        ),
        migrations.AlterField(
            model_name='remoteexperiment',
            name='remote_code',
            field=models.CharField(default='CC4HE38A2R2K', max_length=12, verbose_name='Remote Code'),
        ),
        migrations.AlterField(
            model_name='remoteexperiment',
            name='remote_link',
            field=models.CharField(default='remotelink/CC4HE38A2R2K/', max_length=100, verbose_name='Remote Link'),
        ),
    ]
