# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModME', '0035_add_condition_survey_field_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyfile',
            old_name='task',
            new_name='survey',
        ),
   ]
