# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModME', '0037_add_nasa_tlx_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('name', 'study')]),
        ),
    ]
